services:
    app:
        build:
            target: local
            context: .
        ports:
            - "8081:80"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=gradin_test
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - APP_SEED=true

    db:
        image: postgres:16.2-alpine
        environment:
            - POSTGRES_DB=gradin_test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/postgresql/data

    dbgate:
        container_name: dbgate-gradin
        image: dbgate/dbgate:latest
        environment:
            CONNECTIONS: con1
            LABEL_con1: Postgres
            SERVER_con1: db
            USER_con1: postgres
            PASSWORD_con1: postgres
            PORT_con1: 5432
            ENGINE_con1: postgres@dbgate-plugin-postgres
        ports:
            - 3007:3000
        depends_on:
            db:
                condition: service_healthy

volumes:
    db_data:
